### ISSUE TITLE
Building broken in Manjaro Stable 2020-12-30

### ISSUE THREAD

**Issue by Urs11** [bartoszek/AUR-blender-fracture_modifier-git#2]
Happy New Year!

After upgrading to latest Manjaro, I had to rebuild blender-fracture_modifier-git, but it does not build anymore, can you please have a look?

These 3 types of errors are causing the problem I think:

```
...

In file included from /usr/include/openvdb/Types.h:11,
                 from /usr/include/openvdb/openvdb.h:8,
                 from /home/urs/.cache/yay/blender-fracture_modifier-git/src/blender/intern/openvdb/intern/openvdb_reader.h:29,
                 from /home/urs/.cache/yay/blender-fracture_modifier-git/src/blender/intern/openvdb/intern/openvdb_reader.cc:26:
/usr/include/openvdb/math/Math.h:79:8: error: ‘cwiseAdd’ function uses ‘auto’ type specifier without trailing return type
   79 | inline auto cwiseAdd(const Type1& v, const Type2 s)
      |        ^~~~
      
...      

/usr/include/openvdb/tree/LeafManager.h:800:31: error: ‘make_unique’ is not a member of ‘std’
  800 |             : mLeafOpPtr(std::make_unique<LeafOp>(*(other.mLeafOp), tbb::split()))
      |                               ^~~~~~~~~~~
/usr/include/openvdb/tree/LeafManager.h:800:31: note: ‘std::make_unique’ is only available from C++14 onwards
/usr/include/openvdb/tree/LeafManager.h:800:49: error: expected primary-expression before ‘>’ token
  800 |             : mLeafOpPtr(std::make_unique<LeafOp>(*(other.mLeafOp), tbb::split()))
      |                                                 ^
      

...

ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error making: blender-fracture_modifier-git
```

My current OpenVDB is 7.2.0-1 (has been upgraded from 7.1.0-1, but I did not have to rebuild for some time, so I can't guarantee that this was a working version). In the meantime, I tried **yay --editmenu** to change the PKGBUILD:
commenting out applying the openvdb patch and setting these to OFF:
-DWITH_OPENVDB=OFF \
-DWITH_OPENVDB_BLOSC=OFF \
but even with these changes and clean build, it still fails.

**Comment by bartoszek** [comment]
Thanks for reminding me, `fracture_modifier` branch is stall at 2.7 version and need some patches ported from [AUR-blender-2.7](https://github.com/bartoszek/AUR-blender-2.7/commits/master)
Will look into it tomorrow I presume :smirk:

**Comment by Urs11** [comment]
Sorry, the errors are gone, but it still doesn't build successfully:

```
install: target '/home/urs/.cache/yay/blender-fracture_modifier-git/pkg/blender-fracture_modifier-git/usr/share/blender/2.79_/scripts/addons/' is not a directory: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: blender-fracture_modifier-git
```
The path on my computer is `/home/urs/.cache/yay/blender-fracture_modifier-git/pkg/blender-fracture_modifier-git/usr/share/blender/2.79_@@_sufix@@/scripts/addons/`, guess there is a typo in the PKGBUILD.

**Comment by Urs11** [comment]
It's working now, thank you!

**Comment by bartoszek** [comment]
Jus a typo when refactoring 🤭
